<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?= $title?></title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="public/css/custom.css">
<!--    <script src="public/js/custom.js"></script>-->
</head>
<body>
<div>
    <ul>
        <li><a href="<?=URL?>">Home</a></li>
        <?php if (isset($loggedIn) && $loggedIn): ?>
            <li><a href="<?=URL?>login/logout">logout</a></li>
        <?php else:?>
        <li><a href="<?=URL?>login">Login</a></li>
        <li><a href="<?=URL?>register">Register</a></li>
        <?php endif;?>
<!--        TODO make layout more complex and modular to evade php in html-->

    </ul>
</div>
<div class="container">
    <?= $inner?>
</div>
<footer>
    <hr>
    <p>&copy; ehugh-be 2019</p>
</footer>
</body>
</html>
