<h3>Register</h3>

<form action="<?= URL ?>register" id="register" method="post">
    <label for="login">Login</label><input type="text" id="login" name="login">
    <label for="email">E-mail</label><input type="email" id="email" name="email">
    <label for="password">Password</label><input type="password" id="password" name="passwd">
    <label for="confirm">Confirm password</label><input type="password" id="confirm">
    <input type="submit">
</form>
